/* Generated By:JavaCC: Do not edit this line. SqlParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COPY = 7;
  /** RegularExpression Id. */
  int FROM = 8;
  /** RegularExpression Id. */
  int HEADER = 9;
  /** RegularExpression Id. */
  int TO = 10;
  /** RegularExpression Id. */
  int OBRA = 11;
  /** RegularExpression Id. */
  int CBRA = 12;
  /** RegularExpression Id. */
  int WITH = 13;
  /** RegularExpression Id. */
  int COMMA = 14;
  /** RegularExpression Id. */
  int FORMAT = 15;
  /** RegularExpression Id. */
  int STDIN = 16;
  /** RegularExpression Id. */
  int STDOUT = 17;
  /** RegularExpression Id. */
  int NULL = 18;
  /** RegularExpression Id. */
  int QUOTE = 19;
  /** RegularExpression Id. */
  int ESCAPE = 20;
  /** RegularExpression Id. */
  int TRUE = 21;
  /** RegularExpression Id. */
  int FALSE = 22;
  /** RegularExpression Id. */
  int DELIMITER = 23;
  /** RegularExpression Id. */
  int CSV_OR_TEXT_OR_BINARY = 24;
  /** RegularExpression Id. */
  int NAME = 25;
  /** RegularExpression Id. */
  int ANY_CHAR = 26;
  /** RegularExpression Id. */
  int COMMENT = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"\\\\\"",
    "\"\\t\"",
    "\" \"",
    "\"COPY\"",
    "\"FROM\"",
    "\"HEADER\"",
    "\"TO\"",
    "\"(\"",
    "\")\"",
    "\"WITH\"",
    "\",\"",
    "\"FORMAT\"",
    "\"STDIN\"",
    "\"STDOUT\"",
    "\"NULL\"",
    "\"QUOTE\"",
    "\"ESCAPE\"",
    "<TRUE>",
    "<FALSE>",
    "\"DELIMITER\"",
    "<CSV_OR_TEXT_OR_BINARY>",
    "<NAME>",
    "<ANY_CHAR>",
    "<COMMENT>",
  };

}
